version: '3'
services:
  web:
    container_name: nginx
    build:
      context: deployment/docker/${APP}/nginx
      dockerfile: Dockerfile
    ports:
      - "2095:3000"
    volumes:
      - ./deployment/docker/${APP}/conf/${PROJECT}.conf:/etc/nginx/conf.d/${PROJECT}.conf
      - ./${PROJECT}:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
    depends_on:
      - telegram

  telegram:
    container_name: php
    build:
      context: deployment/docker/${APP}/php
      dockerfile: php-fpm.docker
    volumes:
      - ./${PROJECT}:/var/www/html
    # настройка Xdebug
    environment:
      - PHP_IDE_CONFIG=serverName=php

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: {}