# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Application\Command\TelegramStart: ~
    App\Application\Command\TelegramSetCommand: ~
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
#    Symfony\Component\Serializer\Normalizer\ArrayDenormalizer:
#        tags:
#            - { name: 'serializer.normalizer'}

    App\Application\Service\:
        resource: '../src/Application/Service'

    App\Infrastructure\Client\TelegramBotClient:
        arguments:
            $adminId: '%env(ADMIN_ID)%'
            $botToken: '%env(BOT_TOKEN)%'
            $webhook: '%env(WEB_HOOK)%'

    Predis\Client: '@snc_redis.default'

    _instanceof:
        App\Application\UseCase\CommandHandler:
            tags: [ { name: messenger.message_handler, bus: messenger.bus.command } ]


    App\Infrastructure\Bus\CommandBus:
        arguments:
            - '@messenger.bus.command'

